runner:
  total_steps: 400000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 1000
  eval_step: 500000
  save_step: 2000
  max_keep: 50
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 5.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 4000

downstream_expert:
  datarc:
    speech_commands_root: /root/data2/data/dataset/LibriPhrase/
    # speech_commands_test_root: /root/data1/data/Speech_Group/Dataset/KWS/speech_commands_v1/test
    num_workers: 8
    batch_size: 128

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
